name: data_channel
description: data_channel (DC) is a simple dart utility for handling exceptions and data routing.
version: 2.0.0+1
homepage: https://github.com/ganeshrvel/pub-data-channel

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  # Linting
  lint: ^1.5.3
